#!/bin/bash -e
#
# Dumb hack to get a snapshot of MediaWiki extensions

GERRIT_BASE="https://gerrit.wikimedia.org/r/p/"
# Path where Gerrit replicates repositories:
GIT_BARE_BASE="/srv/ssd/gerrit"

# Helper functions
function warn()  { echo "$@" 1>&2; }
function fatal() { warn "$@"; exit 1; }

# Function fetch an extension under the job workspace
# Parameter: extension name (ex: Validator)
function get_ext {
	GERRIT_URL="$GERRIT_BASE/mediawiki/extensions/$1.git"
	GIT_BARE_DIR="$GIT_BARE_BASE/mediawiki/extensions/$1.git"
	# TODO: make sure that directory exist or die saying the
	# Gerrit replication failed to replicate this extension.
	DEST="$WORKSPACE/extensions/$1"

	# Snapshot `master` in the job workspace

	echo "Deleting and recreating '$DEST'..."
	# Wipe the extension destination directory before applying
	# the archive or deleted file will still be around :/
	rm -fR "$DEST"
	# Recreate the directory for 'git archive'
	mkdir -p "$DEST"

	echo "Copying '$1' in '$DEST'"
	echo "Git archive of 'master' from $GIT_BARE_DIR"
	git archive --remote="$GIT_BARE_DIR" master \
		| (cd "$DEST" && tar xf -)
	echo "Copy complete."
}

# Pre checks
if [ "x$WORKSPACE" == "x" ]; then
	fatal \$WORKSPACE env variable must be set
elif [ ! -d "$WORKSPACE" ]; then
	fatal "$WORKSPACE" is not a directory
fi

# Extract extension names separated by comma
ARGS=$@
IFS=","
mw_exts=($*)

echo "Starting extensions fetches..."
for mw_ext in "${mw_exts[@]}"; do
	echo
	echo "Fetching $mw_ext"
	get_ext "$mw_ext"
done;
echo
echo "Done."
